cqfd: allow to specify a Dockerfile with different filename
docker-build expects the file named Dockerfile at path unless the
argument --file PATH/Dockerfile is given as arguments.

See[1]:

	-f, --file PATH/Dockerfile

	Path to the Dockerfile to use. If the path is a relative path
	and you are building from a local directory, then the path must
	be relative to that directory. If you are building from a remote
	URL pointing to either a tarball or a Git repository, then the
	path must be relative to the root of the remote context. In all
	cases, the file must be within the build context.
	The default is Dockerfile.

podman-build expects the file Containerfile or Dockerfile at path.

See[2]:

	Builds an image using instructions from one or more
	Containerfiles or Dockerfiles and a specified build context
	directory. A Containerfile uses the same syntax as a Dockerfile
	internally. For this document, a file referred to as a
	Containerfile can be a file named either 'Containerfile' or
	'Dockerfile'.

And:

	--file, -f=Containerfile

	Specifies a Containerfile which contains instructions for
	building the image, either a local file or an http or https URL.

	If more than one Containerfile is specified, FROM in‐ structions
	are only be accepted from the last specified file.

	If a build context is not specified, and at least one
	Containerfile is a local file, the directory in which it resides
	is used as the build context.

	Specifying the option -f - causes the Containerfile contents to
	be read from stdin.

cqfd sets --file path/to/file if a build_context is used. Thus, cqfd
requires the file to get named Dockerfile if build_context is unset and
if using docker.

As a consequence, cqfd behaves differently if a build_context is used or
not: the Dockerfile can be named Containerfile if using a build_context,
but it must be named Dockerfile if not using a build_context and if
using docker.

This allows to specify a Dockerfile with a different name (such as
samples/Dockerfile.focalFossa.{nodejs20x,android34}) in any
circumstances; this permits to reuse any Dockerfile files from a
project, and thus, to a possible deprecation of the .cqfd/ directory
structure in the future.

Note: The main purpose of the .cqfd/ directory is to hold the
Dockerfile's in .cqfd/$distro/Dockerfile, and to locate to project
directory (see 4fd3452e656fe684f05f0173136f2b223cf571b6).

This fixes commit 9299823ce661fefa1ac17d6501fde408cedd6a14.

Fixes:

	$ cqfd --init
	[+] Building 0.0s (1/1) FINISHED                                                                                                                                                docker:default
	 => [internal] load build definition from Dockerfile                                                                                                                                      0.0s
	 => => transferring dockerfile: 2B                                                                                                                                                        0.0s
	ERROR: failed to build: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

[1]: https://docs.docker.com/reference/cli/docker/buildx/build/
[2]: https://docs.podman.io/en/stable/markdown/podman-build.1.html