Add cqfd6 symlink
This fixes commit 509d6063feb8fe92f20b78c484531855d3285a98.

Fixes:

	Run rpmdev-setuptree
	  rpmdev-setuptree
	  ver="$(bash cqfd6 --version)"
	  tar czf "../v$ver.tar.gz" --transform "s/./cqfd6-$ver/" .
	  mv "../v$ver.tar.gz" ~/rpmbuild/SOURCES/
	  cp cqfd6.spec ~/rpmbuild/SPECS/
	  cd ~/rpmbuild/SPECS/
	  rpmbuild --undefine=_disable_source_fetch -ba cqfd6.spec
	  cd -
	  cp ~/rpmbuild/SRPMS/*.rpm ~/rpmbuild/RPMS/*/*.rpm .
	  shell: sh -e {0}
	bash: cqfd6: No such file or directory
	Error: Process completed with exit code 127.